[package]
name = "filer-app"
version = "0.2.3"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["tokio", "image"] }
tokio = {workspace = true}
tracing ={ workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
dirs = "6" 
filer-core = { path = "../filer-core", features = ["preview"] }
flume = "0.12"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
iced_lucide = "0.1.0"
