//! # Identity Routes
//!
//! Creates, renames, pairs, and mints pairing PINs for the cookie-backed
//! identity used for write attribution. A stale cookie starts a new identity
//! because database resets and user deletion intentionally return clients to
//! onboarding. Pairing hands an existing identity to a new browser through a
//! short-lived single-use PIN generated by an already-authenticated one.

use axum::{
    Json,
    extract::State,
    http::{HeaderMap, HeaderValue, header::SET_COOKIE},
};
use serde::{Deserialize, Serialize};

use crate::{
    app::AppState,
    error::WebError,
    identity::{Actor, IDENTITY_COOKIE, resolve_optional, session_token},
    storage::{IdentitySession, RedeemOutcome, StorageError, StoredIdentity},
};

const COOKIE_MAX_AGE_SECONDS: u64 = 365 * 24 * 60 * 60;

#[derive(Deserialize)]
pub(crate) struct IdentityRequest {
    username: String,
}

#[derive(Serialize)]
pub(crate) struct IdentityResponse {
    username: String,
}

#[derive(Deserialize)]
pub(crate) struct PairRequest {
    username: String,
    pin: String,
}

#[derive(Serialize)]
pub(crate) struct PairingPinResponse {
    pin: String,
    expires_at: i64,
}

pub(crate) async fn get_identity(actor: Actor) -> Json<IdentityResponse> {
    Json(IdentityResponse {
        username: actor.username,
    })
}

pub(crate) async fn put_identity(
    State(state): State<AppState>,
    headers: HeaderMap,
    Json(request): Json<IdentityRequest>,
) -> Result<(HeaderMap, Json<IdentityResponse>), WebError> {
    let username = validate_username(&request.username)?;
    let existing = resolve_optional(&headers, &state).await?;
    let (identity, token) = match existing {
        Some(actor) => rename_or_recover(&state, &headers, actor, &username).await?,
        None => create(&state, &username).await?,
    };
    let mut response_headers = HeaderMap::new();
    response_headers.insert(SET_COOKIE, identity_cookie(&token)?);
    Ok((
        response_headers,
        Json(IdentityResponse {
            username: identity.username,
        }),
    ))
}

pub(crate) async fn mint_pairing_pin(
    State(state): State<AppState>,
    actor: Actor,
) -> Result<Json<PairingPinResponse>, WebError> {
    let pairing = state
        .storage()
        .mint_pairing_pin(actor.user_id, actor.session_id)
        .await?;
    Ok(Json(PairingPinResponse {
        pin: pairing.pin,
        expires_at: pairing.expires_at,
    }))
}

pub(crate) async fn pair_identity(
    State(state): State<AppState>,
    Json(request): Json<PairRequest>,
) -> Result<(HeaderMap, Json<IdentityResponse>), WebError> {
    let username = validate_username(&request.username)?;
    let pin = validate_pin(&request.pin)?;
    let outcome = state.storage().redeem_pairing_pin(&username, &pin).await?;
    let session = match outcome {
        RedeemOutcome::Session(session) => session,
        RedeemOutcome::UnknownUsername => return Err(WebError::PairingUnknownUsername),
        RedeemOutcome::WrongPin => return Err(WebError::PairingPinWrong),
        RedeemOutcome::Expired => return Err(WebError::PairingPinExpired),
        RedeemOutcome::Consumed => return Err(WebError::PairingPinConsumed),
        RedeemOutcome::Locked => return Err(WebError::PairingPinLocked),
    };
    let mut response_headers = HeaderMap::new();
    response_headers.insert(SET_COOKIE, identity_cookie(&session.session_token)?);
    Ok((
        response_headers,
        Json(IdentityResponse {
            username: session.identity.username,
        }),
    ))
}

async fn rename_or_recover(
    state: &AppState,
    headers: &HeaderMap,
    actor: Actor,
    username: &str,
) -> Result<(StoredIdentity, String), WebError> {
    match state
        .storage()
        .rename_identity(actor.user_id, username)
        .await
    {
        Ok(identity) => {
            let token = session_token(headers)
                .ok_or_else(|| WebError::Internal("resolved identity had no cookie".to_string()))?;
            Ok((identity, token.to_string()))
        }
        Err(StorageError::IdentityNotFound(_)) => create(state, username).await,
        Err(error) => Err(error.into()),
    }
}

async fn create(state: &AppState, username: &str) -> Result<(StoredIdentity, String), WebError> {
    let IdentitySession {
        identity,
        session_token,
    } = state.storage().create_identity(username).await?;
    Ok((identity, session_token))
}

fn validate_username(value: &str) -> Result<String, WebError> {
    let username = value.trim();
    let length = username.chars().count();
    if !(1..=64).contains(&length) {
        return Err(WebError::InvalidUsername(
            "username must contain between 1 and 64 characters".to_string(),
        ));
    }
    if username.chars().any(char::is_control) {
        return Err(WebError::InvalidUsername(
            "username must not contain control characters".to_string(),
        ));
    }
    Ok(username.to_string())
}

fn validate_pin(value: &str) -> Result<String, WebError> {
    let pin = value.trim();
    if pin.len() != 6 || !pin.chars().all(|digit| digit.is_ascii_digit()) {
        return Err(WebError::PairingPinWrong);
    }
    Ok(pin.to_string())
}

fn identity_cookie(token: &str) -> Result<HeaderValue, WebError> {
    let cookie = format!(
        "{IDENTITY_COOKIE}={token}; Max-Age={COOKIE_MAX_AGE_SECONDS}; HttpOnly; SameSite=Lax; Path=/"
    );
    HeaderValue::from_str(&cookie)
        .map_err(|error| WebError::Internal(format!("identity cookie was invalid: {error}")))
}
